"""add_rag_configs_table

Revision ID: 962e5b26ffd2
Revises: 002
Create Date: 2025-12-02 10:32:28.397623

"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "962e5b26ffd2"
down_revision = "002"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rag_configs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("provider_type", sa.String(length=20), nullable=False),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("provider_config", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_rag_configs_is_default", "rag_configs", ["is_default"], unique=False, postgresql_where=sa.text("is_default IS true"))
    op.create_index("idx_rag_configs_user_default", "rag_configs", ["user_id"], unique=True, postgresql_where=sa.text("is_default IS true"))
    op.create_index("idx_rag_configs_user_id", "rag_configs", ["user_id"], unique=False)

    # Conditionally drop indexes and tables that may not exist
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    # Drop indexes on global_provider_configs if they exist
    if "global_provider_configs" in inspector.get_table_names():
        index_names = [idx["name"] for idx in inspector.get_indexes("global_provider_configs")]
        if "idx_global_provider_configs_name" in index_names:
            op.drop_index("idx_global_provider_configs_name", table_name="global_provider_configs")
        if "idx_global_provider_configs_type" in index_names:
            op.drop_index("idx_global_provider_configs_type", table_name="global_provider_configs")
        if "idx_global_provider_configs_user" in index_names:
            op.drop_index("idx_global_provider_configs_user", table_name="global_provider_configs")
        op.drop_table("global_provider_configs")

    # Drop indexes on provider_setting_templates if they exist
    if "provider_setting_templates" in inspector.get_table_names():
        index_names = [idx["name"] for idx in inspector.get_indexes("provider_setting_templates")]
        if "idx_provider_templates_name" in index_names:
            op.drop_index("idx_provider_templates_name", table_name="provider_setting_templates")
        if "idx_provider_templates_type" in index_names:
            op.drop_index("idx_provider_templates_type", table_name="provider_setting_templates")
        op.drop_table("provider_setting_templates")

    op.add_column("agents", sa.Column("rag_config_id", sa.UUID(), nullable=True))
    op.create_foreign_key(None, "agents", "rag_configs", ["rag_config_id"], ["id"], ondelete="SET NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "agents", type_="foreignkey")
    op.drop_column("agents", "rag_config_id")

    bind = op.get_bind()
    inspector = sa.inspect(bind)

    # Recreate provider_setting_templates only if it doesn't exist
    if "provider_setting_templates" not in inspector.get_table_names():
        op.create_table(
            "provider_setting_templates",
            sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
            sa.Column("provider_type", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
            sa.Column("provider_name", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
            sa.Column("setting_name", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
            sa.Column("setting_type", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
            sa.Column("default_value", sa.TEXT(), autoincrement=False, nullable=True),
            sa.Column("description", sa.TEXT(), autoincrement=False, nullable=True),
            sa.Column("is_required", sa.BOOLEAN(), server_default=sa.text("false"), autoincrement=False, nullable=False),
            sa.Column("validation_rules", postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
            sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), autoincrement=False, nullable=True),
            sa.PrimaryKeyConstraint("id", name=op.f("provider_setting_templates_pkey")),
            sa.UniqueConstraint("provider_type", "provider_name", "setting_name", name=op.f("unique_setting_template"), postgresql_include=[], postgresql_nulls_not_distinct=False),
        )
        op.create_index(op.f("idx_provider_templates_type"), "provider_setting_templates", ["provider_type"], unique=False)
        op.create_index(op.f("idx_provider_templates_name"), "provider_setting_templates", ["provider_name"], unique=False)

    # Recreate global_provider_configs only if it doesn't exist
    if "global_provider_configs" not in inspector.get_table_names():
        op.create_table(
            "global_provider_configs",
            sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
            sa.Column("provider_type", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
            sa.Column("provider_name", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
            sa.Column("settings", postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
            sa.Column("is_active", sa.BOOLEAN(), server_default=sa.text("true"), autoincrement=False, nullable=False),
            sa.Column("user_id", sa.VARCHAR(length=100), autoincrement=False, nullable=True),
            sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), autoincrement=False, nullable=True),
            sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), autoincrement=False, nullable=True),
            sa.PrimaryKeyConstraint("id", name=op.f("global_provider_configs_pkey")),
            sa.UniqueConstraint("provider_type", "provider_name", name=op.f("unique_provider_config"), postgresql_include=[], postgresql_nulls_not_distinct=False),
        )
        op.create_index(op.f("idx_global_provider_configs_user"), "global_provider_configs", ["user_id"], unique=False)
        op.create_index(op.f("idx_global_provider_configs_type"), "global_provider_configs", ["provider_type"], unique=False)
        op.create_index(op.f("idx_global_provider_configs_name"), "global_provider_configs", ["provider_name"], unique=False)

    op.drop_index("idx_rag_configs_user_id", table_name="rag_configs")
    op.drop_index("idx_rag_configs_user_default", table_name="rag_configs", postgresql_where=sa.text("is_default IS true"))
    op.drop_index("idx_rag_configs_is_default", table_name="rag_configs", postgresql_where=sa.text("is_default IS true"))
    op.drop_table("rag_configs")
    # ### end Alembic commands ###
